### PR TITLE
Add Tentative Specifications

### PR DESCRIPTION
**Pull request by anssiko**
- Add Model Loader API
- Add Web Neural Network API Lower-level Instruction Set

### CODE REVIEW

**Comment by jbingham** [comment]
@anssiko This looks good. What would be the process if we decided to propose any other APIs beyond those mentioned explicitly?

**Comment by anssiko** [comment]
Thanks @jbingham for your swift review.

@dontcallmedom do you have suggestions re @jbingham's question:

>What would be the process if we decided to propose any other APIs beyond those mentioned explicitly?

**Comment by dontcallmedom** [comment]
@jbingham do you mean proposing additional APIs before the charter is brought for W3C's adoption, or after?

Until we start the formal process of getting the charter approved, we can add other APIs if they look like realistic targets - by realistic, I mean that they don't expand the IPR scope of the charter to the point that they would create participation barriers, and that such APIs would be likely to get enough incubation within the duration of the charter (typically 2 years) to be adoptable in that timeframe.

Once the charter is under review or once it is approved, adding new deliverables requires rechartering **if** the said deliverables don't fit within the expressed scope of the charter. There may be room for tweaking the scope to make this more likely (again, ideally, while not opening it up so broadly that the IPR scope would become challenging).

**Comment by jbingham** [comment]
A concrete example:
- what if we decide to launch a convolution 2D operation as a standalone API, independent of Web NN or a model loader? would that require rechartering? 

Some of the benchmarking suggests there are a few specific operations (like convolution and matrix multiplication) that could give a 90% or more performance boost without a larger API surface. It would be nice if we had the flexibility to define those APIs with rechartering later.

**Comment by anssiko** [comment]
I believe @jbingham's question asks whether the WG could decide later to advance only a subset of an API in scope without rechartering the WG. Based on my understanding, the WG could do that without rechartering, but I'll let @dontcallmedom chime in whether there are some special considerations.

**Comment by dontcallmedom** [comment]
I confirm @anssiko 's assessment that there would be no need to recharter if we were to focus on a subset of the API.

**Comment by jbingham** [comment]
Great, thanks for confirming, @anssiko  and @dontcallmedom . This PR now addresses everything I can think of that we might want to cover. LGTM.

**Comment by anssiko** [comment]
@jbingham could you open an issue in the [proposals](https://github.com/webmachinelearning/proposals) repo that introduces the Web Neural Network API Lower-level Instruction Set proposal and in particular explains in a concise way the related work that is expected to influence this proposal?

This is helpful for the purpose of the charter review, where potentially 400+ W3C Member companies will take a look at the charter and want to understand the scope of work. The discussion threads such as those linked to from https://github.com/w3c/machine-learning-charter/issues/7#issuecomment-726372386 will overwhelm those folks who'll be reviewing the charter, so I'd prefer not to link to them from the charter.

**Comment by anssiko** [comment]
Per discussion on the [WebML CG Teleconference – 10 December 2020](https://www.w3.org/2020/12/10-webmachinelearning-minutes.html) this PR can be merged.

This PR addresses issue #8.

**Comment by wchao1115** [comment]
@anssiko Maybe I'm mistaken but I believe I've explained in the 12/10 call that the notion of low-level operations as stated with the examples of XLA-HLO, Tensor Compute, and TOSA, have already been incorporated in the design of the WebNN operations in the spec to which others have agreed in the call. The following is the relevant portion of the conversation as captured in the [meeting minute](https://www.w3.org/2020/12/10-webmachinelearning-minutes.html):

> <dom> **Chai: I have questions**
<dom> ... reading this issue, it seems like the request would be extended to support low level instructions
<dom> ... **there has been a lot of discussions on low vs high level already
<dom> ... and it has been pointed out that the "low level" set is not really lower level than what WebNN provides**
<dom> ... I also don't understand the relation to subsetting WebNN and this low-vs-high level
<dom> ... I understand there was discussion on whether WebNN would be low level enough and whether a graph API is the right approach
<dom> ... I'm not sure how this addresses that question (which I think has been otherwise addressed in the discussion)
<dom> Anssi: Jonathan you had suggested shipping a subset of WebNN that would perform better - can you speak to that?
<dom> **Jonathan**: 3 topics: whether the operations are low-level enough - **I agree with Chai that low level operations can be addressed in a graph API, so that issue can be closed**

The exact wording of the change also implies that once the so-called low-level instruction set is defined, WebNN would be bound to the notion that it is therefore defined in term of this low-level instruction set.

>*A lower-level instruction set* for the Web Neural Network API
                defines a complementary **set of primitives out of which
                higher-level operations defined by the Web Neural Network API
                can be constructed**

I believe this would lead to confusion down the road, and could potentially induce divergence to the way WebNN API is implemented by the web browsers.

Note that the fundamental promise of the WebNN API, as clearly articulated in the [explainer](https://github.com/webmachinelearning/webnn/blob/master/explainer.md), is to be the *ML abstraction that enables native acceleration in the underlying platform*, and not merely as a wrapper API to a lower level instruction set. 

I believe this change should be retracted from the charter. @rafaelcintron, @gramalingam

**Comment by anssiko** [comment]
@wchao1115, thanks for your feedback! I probably misinterpreted this part of the discussion.

To clear this bit, I just had a discussion with @jbingham about this PR and @jbingham seems to agree the "Web Neural Network API Lower-level Instruction Set" tentative deliverable is not necessary to be called out as a separate spec in the proposed WG Charter.

To that end, I've crafted a PR to remove the said "Web Neural Network API Lower-level Instruction Set" tentative deliverable from the proposed WG Charter, leaving in the "Model Loader API" as a tentative deliverable.

PTAL: https://github.com/w3c/machine-learning-charter/pull/12

**Pull request merged**
